name: ron

services:
  ron:
    container_name: ron
    image: ghcr.io/slugsoc/slugs-discord-bot:master
    volumes:
      - ./token.yaml:/app/token.yaml
      - ./logs:/app/logs
      - ./server_configs:/app/server_configs
    restart: unless-stopped